### ISSUE TITLE
Created a new transform, transform2

### ISSUE THREAD

**Issue by tobgu** [boxed/instar-py#1]
That can probably replace set_in in pyrsistent once we get pvector support in. Should be fairly trivial but I want to change the evolver interface slightly first. No time right now. Maybe tomorrow.

Also added rex support.

Please have a look.

**Comment by boxed** [comment]
You know what would be great? If somepmap.evolve() let you get something that was recursive evolvable. 

```python
>>> freeze({'a': {'b': 1}})
pmap({'a': pmap({'b': 1})})
>>> x = freeze({'a': {'b': 1}})
>>> e = x.evolver()
>>> e['a']['b'] = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'PMap' object does not support item assignment
```

If this could be supported it would make everything much easier I think, plus it would make it nicer to pass in an evolver into legacy code that mutates nested dicts.

**Comment by tobgu** [comment]
Yes, the thought has struck me about a 100 times. :-) Not trivial to make it performant in combination with generic I think but it would be a nice feature. Will think some more about it, please let me know if you have any brilliant thoughts.

Just updated the transform2() to support pvectors as well.

Also noted that you do not make use of Clojures transient structures in instar. That could potentially speed up operations I think.

**Comment by boxed** [comment]
To me it seems like .evolver() is really just a lazy thaw. I don't know how fast those evolvers are but how do a PMap evolved compare to just having a dict with the "new" data and any data that's not in this dict is read from the backing PMap?

Cool.

re transients: tried to use them. Couldn't figure out how to do even trivial operations so I gave up and wrote my own stack backed by ArrayList in java and an array in js.. that's been refactored away now though.

**Comment by tobgu** [comment]
I think the main difference between an evolver and a lazy thaw would be that no structural sharing would take place between the old and the new version in the case of a lazy thaw while the evolver tries to maximize structural sharing between them.

**Comment by boxed** [comment]
Well.. depends on the granularity of the lazyness... you could think of it as per-element lazy thaw. That would maximize structural sharing, no?

**Comment by tobgu** [comment]
Yes, but then it would not be a thaw as implemented right now since it is
thawing per structure. Should be possible to write something like what you
want on top of the evolver I think. You just have to add an additional
layer to keep track of updates, inserts and deletes and then commit it all
in the end. Like the dict you mentioned. It's just that this thing will
have to implement some stuff to appear as a dict/list/whatever...


2015-01-12 9:09 GMT+01:00 Anders Hovmöller <notifications@github.com>:

**Comment by boxed** [comment]
I'm assuming this is irrelevant now that most/all of this projects ideas are in pyrsistent.
